{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "coredns.fullname" . }}
  {{- if .Values.prometheus.monitor.namespace }}
  namespace: {{ .Values.prometheus.monitor.namespace }}
  {{- end }}
  labels:
{{- include "coredns.labels" . | nindent 4 }}
    {{- if .Values.prometheus.monitor.additionalLabels }}
{{ toYaml .Values.prometheus.monitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
{{- include "coredns.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
{{- end }}
